let firstName="divya";
let companyname="veeva";
let mobileNumber="1234";
let isAutomation=true;
let hasPlawright;
console.log(isAutomation , typeof isAutomation);
console.log(companyname, typeof companyname);
console.log(mobileNumber, typeof companyname);
console.log(firstName, typeof firstName);
console.log(hasPlawright, typeof hasPlawright);